server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shoppingmall?serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
    data: classpath:data.sql
    mode: always
    console:
      enable: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always # ?? ??? ?? classpath? sql?? ????? ??
      continue-on-error: true # ?? ??? sql?? ??? ? ?? ???? ?? ??
      data-locations: classpath:sql/data.sql # ?? ??? dml sql?? ??? ?? ? ?? ??

